http_port 3128
acl allowed_ports port 80 443
http_access deny !allowed_ports
acl private dst 0.0.0.0/8
acl private dst 10.0.0.0/8
acl private dst 127.0.0.0/8
acl private dst 169.254.0.0/16
acl private dst 172.16.0.0/12
acl private dst 192.168.0.0/16
acl private dst ::1/128
acl private dst fc00::/7
acl private dst fe80::/10
http_access deny private
http_access allow all
cache deny all
via off
forwarded_for delete
