from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class Week2ErrorCode(str, Enum):
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    HTTP_ERROR = "HTTP_ERROR"
    INVALID_REQUEST = "INVALID_REQUEST"

    AUTH_REQUIRED = "AUTH_REQUIRED"
    ACCESS_TOKEN_EXPIRED = "ACCESS_TOKEN_EXPIRED"  # nosec B105
    ACCESS_TOKEN_NOT_YET_VALID = "ACCESS_TOKEN_NOT_YET_VALID"  # nosec B105
    INVALID_ACCESS_TOKEN = "INVALID_ACCESS_TOKEN"  # nosec B105
    TOKEN_REVOKED = "TOKEN_REVOKED"  # nosec B105
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"
    USER_DISABLED = "USER_DISABLED"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    ROLE_ASSIGNMENT_REQUIRED = "ROLE_ASSIGNMENT_REQUIRED"
    AUTH_USER_LOCKED = "AUTH_USER_LOCKED"
    AUTH_USER_NOT_ACTIVE = "AUTH_USER_NOT_ACTIVE"
    INVALID_EMAIL = "INVALID_EMAIL"
    INVALID_PASSWORD = "INVALID_PASSWORD"  # nosec B105
    REFRESH_TOKEN_REQUIRED = "REFRESH_TOKEN_REQUIRED"  # nosec B105
    INVALID_REFRESH_TOKEN = "INVALID_REFRESH_TOKEN"  # nosec B105
    REFRESH_TOKEN_EXPIRED = "REFRESH_TOKEN_EXPIRED"  # nosec B105
    REFRESH_TOKEN_REUSED = "REFRESH_TOKEN_REUSED"  # nosec B105
    REFRESH_TOKEN_REVOKED = "REFRESH_TOKEN_REVOKED"  # nosec B105
    INVALID_API_KEY = "INVALID_API_KEY"  # nosec B105
    EXPIRED_API_KEY = "EXPIRED_API_KEY"  # nosec B105
    INVALID_2FA_TOKEN = "INVALID_2FA_TOKEN"  # nosec B105
    INVALID_TOTP_CODE = "INVALID_TOTP_CODE"  # nosec B105
    _2FA_TOKEN_EXPIRED = "2FA_TOKEN_EXPIRED"  # nosec B105
    _2FA_ALREADY_ENABLED = "2FA_ALREADY_ENABLED"
    _2FA_NOT_ENABLED = "2FA_NOT_ENABLED"
    _2FA_NOT_SETUP = "2FA_NOT_SETUP"
    _2FA_SECRET_UNAVAILABLE = "2FA_SECRET_UNAVAILABLE"  # nosec B105

    TENANT_REQUIRED = "TENANT_REQUIRED"
    INVALID_TENANT_ID = "INVALID_TENANT_ID"
    TENANT_DISABLED = "TENANT_DISABLED"
    TENANT_SCOPE_MISMATCH = "TENANT_SCOPE_MISMATCH"
    FORBIDDEN = "FORBIDDEN"
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"

    IDEMPOTENCY_KEY_REQUIRED = "IDEMPOTENCY_KEY_REQUIRED"
    IDEMPOTENCY_KEY_INVALID = "IDEMPOTENCY_KEY_INVALID"
    IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT"

    INVALID_UPLOAD_FILENAME = "INVALID_UPLOAD_FILENAME"
    INVALID_UPLOAD_TYPE = "INVALID_UPLOAD_TYPE"
    INVALID_UPLOAD_SIGNATURE = "INVALID_UPLOAD_SIGNATURE"
    ARCHIVE_BOMB_DETECTED = "ARCHIVE_BOMB_DETECTED"
    ACTIVE_CONTENT_DETECTED = "ACTIVE_CONTENT_DETECTED"
    CORRUPTED_ARCHIVE = "CORRUPTED_ARCHIVE"
    ZIP_SLIP_DETECTED = "ZIP_SLIP_DETECTED"
    DOC_TOO_LARGE = "DOC_TOO_LARGE"
    MALWARE_SCAN_FAILED = "MALWARE_SCAN_FAILED"
    QUOTA_EXCEEDED = "QUOTA_EXCEEDED"

    STORAGE_UNAVAILABLE = "STORAGE_UNAVAILABLE"
    STORAGE_OBJECT_NOT_FOUND = "STORAGE_OBJECT_NOT_FOUND"
    INGESTION_QUEUE_UNAVAILABLE = "INGESTION_QUEUE_UNAVAILABLE"

    UNSUPPORTED_DOCUMENT_TYPE = "UNSUPPORTED_DOCUMENT_TYPE"
    PDF_PARSE_FAILED = "PDF_PARSE_FAILED"
    DOCX_PARSE_FAILED = "DOCX_PARSE_FAILED"
    PPTX_PARSE_FAILED = "PPTX_PARSE_FAILED"
    XLSX_PARSE_FAILED = "XLSX_PARSE_FAILED"
    DOCX_EXTRACTOR_DEPENDENCY_MISSING = "DOCX_EXTRACTOR_DEPENDENCY_MISSING"
    PPTX_EXTRACTOR_DEPENDENCY_MISSING = "PPTX_EXTRACTOR_DEPENDENCY_MISSING"
    XLSX_EXTRACTOR_DEPENDENCY_MISSING = "XLSX_EXTRACTOR_DEPENDENCY_MISSING"
    LEGACY_CONVERSION_UNSUPPORTED = "LEGACY_CONVERSION_UNSUPPORTED"
    LEGACY_CONVERSION_DISABLED = "LEGACY_CONVERSION_DISABLED"
    LEGACY_CONVERSION_UNAVAILABLE = "LEGACY_CONVERSION_UNAVAILABLE"
    LEGACY_CONVERSION_TIMEOUT = "LEGACY_CONVERSION_TIMEOUT"
    LEGACY_CONVERSION_FAILED = "LEGACY_CONVERSION_FAILED"
    OCR_UNAVAILABLE = "OCR_UNAVAILABLE"
    OCR_TIMEOUT = "OCR_TIMEOUT"
    OCR_FAILED = "OCR_FAILED"
    OCR_PAGE_LIMIT_EXCEEDED = "OCR_PAGE_LIMIT_EXCEEDED"
    IMAGE_PARSE_FAILED = "IMAGE_PARSE_FAILED"
    VISION_UNAVAILABLE = "VISION_UNAVAILABLE"
    VISION_TIMEOUT = "VISION_TIMEOUT"
    VISION_FAILED = "VISION_FAILED"
    PDF_PAGE_LIMIT_EXCEEDED = "PDF_PAGE_LIMIT_EXCEEDED"
    DOCUMENT_TEXT_LIMIT_EXCEEDED = "DOCUMENT_TEXT_LIMIT_EXCEEDED"
    DOCUMENT_EMPTY_AFTER_PARSE = "DOCUMENT_EMPTY_AFTER_PARSE"
    NO_VALID_CHUNKS = "NO_VALID_CHUNKS"

    EMBEDDING_PROVIDER_UNAVAILABLE = "EMBEDDING_PROVIDER_UNAVAILABLE"
    EMBEDDING_PROVIDER_NOT_CONFIGURED = "EMBEDDING_PROVIDER_NOT_CONFIGURED"
    EMBEDDING_DIMENSION_MISMATCH = "EMBEDDING_DIMENSION_MISMATCH"
    EMBEDDING_CIRCUIT_OPEN = "EMBEDDING_CIRCUIT_OPEN"
    EMBEDDING_REQUEST_INVALID = "EMBEDDING_REQUEST_INVALID"
    PROVIDER_CIRCUIT_OPEN = "PROVIDER_CIRCUIT_OPEN"
    PROVIDER_TIMEOUT = "PROVIDER_TIMEOUT"
    PROVIDER_NOT_FOUND = "PROVIDER_NOT_FOUND"
    PROVIDER_UNSUPPORTED_TYPE = "PROVIDER_UNSUPPORTED_TYPE"
    PROVIDER_AUTH_MODE_NOT_ALLOWED = "PROVIDER_AUTH_MODE_NOT_ALLOWED"
    PROVIDER_MODEL_PULL_UNSUPPORTED = "PROVIDER_MODEL_PULL_UNSUPPORTED"
    PROVIDER_OAUTH_UNSUPPORTED = "PROVIDER_OAUTH_UNSUPPORTED"
    PROVIDER_TEST_FAILED = "PROVIDER_TEST_FAILED"
    PROVIDER_ASSIGNMENT_INVALID = "PROVIDER_ASSIGNMENT_INVALID"
    PROVIDER_SECRET_REQUIRED = "PROVIDER_SECRET_REQUIRED"  # nosec B105
    PROVIDER_SECRET_STORAGE_UNAVAILABLE = (
        "PROVIDER_SECRET_STORAGE_UNAVAILABLE"  # nosec B105
    )
    PROVIDER_IN_USE = "PROVIDER_IN_USE"
    PROVIDER_HEALTH_CHECK_FAILED = "PROVIDER_HEALTH_CHECK_FAILED"
    CONNECTOR_OAUTH_UNSUPPORTED = "CONNECTOR_OAUTH_UNSUPPORTED"
    CONNECTOR_OAUTH_INVALID = "CONNECTOR_OAUTH_INVALID"
    CONNECTOR_OAUTH_TOKEN_EXCHANGE_FAILED = "CONNECTOR_OAUTH_TOKEN_EXCHANGE_FAILED"
    DUPLICATE_CONNECTION = "DUPLICATE_CONNECTION"
    DURABLE_RUN_FORBIDDEN = "DURABLE_RUN_FORBIDDEN"
    DURABLE_RUN_NOT_FOUND = "DURABLE_RUN_NOT_FOUND"
    NOT_FOUND = "NOT_FOUND"
    SERVICE_OVERLOAD = "SERVICE_OVERLOAD"

    DOCUMENT_NOT_FOUND = "DOCUMENT_NOT_FOUND"
    COLLECTION_NOT_FOUND = "COLLECTION_NOT_FOUND"
    COLLECTION_NOTIFICATION_NOT_FOUND = "COLLECTION_NOTIFICATION_NOT_FOUND"
    INVALID_COLLECTION_MEMBER = "INVALID_COLLECTION_MEMBER"
    COLLECTION_BRIDGE_FULL = "COLLECTION_BRIDGE_FULL"
    COLLECTION_BRIDGE_PENDING = "COLLECTION_BRIDGE_PENDING"
    COLLECTION_BRIDGE_EXISTS = "COLLECTION_BRIDGE_EXISTS"
    CITATION_NOT_FOUND = "CITATION_NOT_FOUND"
    INVALID_FILTER_FIELD = "INVALID_FILTER_FIELD"
    TOP_K_OUT_OF_RANGE = "TOP_K_OUT_OF_RANGE"
    QUERY_VALIDATION_ERROR = "QUERY_VALIDATION_ERROR"
    LLM_UNAVAILABLE = "LLM_UNAVAILABLE"
    DATA_DELETION_NOT_FOUND = "DATA_DELETION_NOT_FOUND"
    DELETION_FAILED = "DELETION_FAILED"
    DATABASE_NOT_READY = "DATABASE_NOT_READY"
    REDIS_NOT_READY = "REDIS_NOT_READY"
    INGESTION_UNEXPECTED_ERROR = "INGESTION_UNEXPECTED_ERROR"
    SUPERSEDED_JOB = "SUPERSEDED_JOB"
    CONVERSATION_NOT_FOUND = "CONVERSATION_NOT_FOUND"
    MESSAGE_NOT_FOUND = "MESSAGE_NOT_FOUND"
    MESSAGE_VERSION_NOT_FOUND = "MESSAGE_VERSION_NOT_FOUND"
    MESSAGE_EDIT_NOT_ALLOWED = "MESSAGE_EDIT_NOT_ALLOWED"
    MESSAGE_REGENERATE_NOT_ALLOWED = "MESSAGE_REGENERATE_NOT_ALLOWED"
    INVALID_MESSAGE_ROLE = "INVALID_MESSAGE_ROLE"
    TURN_NOT_FOUND = "TURN_NOT_FOUND"
    STREAM_LLM_UNAVAILABLE = "STREAM_LLM_UNAVAILABLE"
    STREAM_PROVIDER_FAILURE = "STREAM_PROVIDER_FAILURE"
    STREAM_RETRYABLE_FAILURE = "STREAM_RETRYABLE_FAILURE"
    STREAM_EMPTY_PROVIDER_RESPONSE = "STREAM_EMPTY_PROVIDER_RESPONSE"
    WS_ENDPOINT_NOT_SUPPORTED = "WS_ENDPOINT_NOT_SUPPORTED"
    DEEPSPACE_WEBSOCKET_FAILURE = "DEEPSPACE_WEBSOCKET_FAILURE"
    MISSION_NOT_FOUND = "MISSION_NOT_FOUND"
    MISSION_VALIDATION_ERROR = "MISSION_VALIDATION_ERROR"
    MISSION_FORBIDDEN = "MISSION_FORBIDDEN"
    SUBAGENT_RUN_NOT_FOUND = "SUBAGENT_RUN_NOT_FOUND"
    SUBAGENT_RUN_FORBIDDEN = "SUBAGENT_RUN_FORBIDDEN"
    PENDING_TOOL_NOT_FOUND = "PENDING_TOOL_NOT_FOUND"
    RESUME_VALIDATION_ERROR = "RESUME_VALIDATION_ERROR"
    TASK_NOT_FOUND = "TASK_NOT_FOUND"
    MEMORY_NOT_FOUND = "MEMORY_NOT_FOUND"
    STORAGE_MISSING = "STORAGE_MISSING"
    BREAK_GLASS_GRANT_NOT_FOUND = "BREAK_GLASS_GRANT_NOT_FOUND"
    COMMENT_TARGET_NOT_ACCESSIBLE = "COMMENT_TARGET_NOT_ACCESSIBLE"
    QUERY_NOT_ACCESSIBLE = "QUERY_NOT_ACCESSIBLE"
    PROVIDER_CONFIG_NOT_FOUND = "PROVIDER_CONFIG_NOT_FOUND"


WEEK2_ERROR_CODES: frozenset[str] = frozenset(code.value for code in Week2ErrorCode)


def is_week2_error_code(code: str) -> bool:
    return code in WEEK2_ERROR_CODES


def is_known_error_code(code: str) -> bool:
    return is_week2_error_code(code)


class ErrorBody(BaseModel):
    code: str
    message: str
    details: dict[str, Any] = Field(default_factory=dict)

    model_config = ConfigDict(extra="forbid")


class ErrorResponse(BaseModel):
    error: ErrorBody
    trace_id: str | None
    timestamp: str

    model_config = ConfigDict(extra="forbid")
