"""D_8_advanced_feedback_loop

Revision ID: 01f79624986f
Revises: 1353db0b26f6
Create Date: 2026-03-06 01:08:21.140928
"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "01f79624986f"
down_revision = "1353db0b26f6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document_chunks", sa.Column("quality_score", sa.Float(), nullable=True)
    )
    op.add_column(
        "query_citations", sa.Column("feedback_score", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("query_citations", "feedback_score")
    op.drop_column("document_chunks", "quality_score")
    # ### end Alembic commands ###
