"""Add document hub observability fields

Revision ID: 0f4d468f8713
Revises: 01f79624986f
Create Date: 2026-03-06 14:06:12.432201
"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0f4d468f8713"
down_revision = "01f79624986f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents",
        sa.Column(
            "processing_progress",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
    )
    op.add_column(
        "documents",
        sa.Column(
            "quarantined", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    op.add_column(
        "documents", sa.Column("information_yield", sa.Float(), nullable=True)
    )
    op.add_column(
        "documents",
        sa.Column(
            "is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "is_deleted")
    op.drop_column("documents", "information_yield")
    op.drop_column("documents", "quarantined")
    op.drop_column("documents", "processing_progress")
    # ### end Alembic commands ###
