"""D_6_multilingual_document_language

Revision ID: 1353db0b26f6
Revises: b6a717a0a8bf
Create Date: 2026-03-06 01:03:55.045611
"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "1353db0b26f6"
down_revision = "b6a717a0a8bf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents", sa.Column("language", sa.String(length=16), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "language")
    # ### end Alembic commands ###
