"""D_3_collaborative_workspace

Revision ID: 2f6f3403926e
Revises: 96a6a4be2b6a
Create Date: 2026-03-06 00:30:12.511722
"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "2f6f3403926e"
down_revision = "96a6a4be2b6a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("target_type", sa.String(length=32), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["parent_id"], ["comments.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_comments_target_id"), "comments", ["target_id"], unique=False)
    op.create_index(op.f("ix_comments_tenant_id"), "comments", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_comments_user_id"), "comments", ["user_id"], unique=False)
    op.create_table(
        "pinned_findings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("query_id", sa.UUID(), nullable=False),
        sa.Column("chunk_id", sa.UUID(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["query_id"], ["queries.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pinned_findings_query_id"),
        "pinned_findings",
        ["query_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pinned_findings_tenant_id"),
        "pinned_findings",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pinned_findings_user_id"), "pinned_findings", ["user_id"], unique=False
    )
    op.add_column(
        "queries",
        sa.Column(
            "shared_with",
            sa.ARRAY(sa.UUID()),
            server_default=sa.text("'{}'::uuid[]"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("queries", "shared_with")
    op.drop_index(op.f("ix_pinned_findings_user_id"), table_name="pinned_findings")
    op.drop_index(op.f("ix_pinned_findings_tenant_id"), table_name="pinned_findings")
    op.drop_index(op.f("ix_pinned_findings_query_id"), table_name="pinned_findings")
    op.drop_table("pinned_findings")
    op.drop_index(op.f("ix_comments_user_id"), table_name="comments")
    op.drop_index(op.f("ix_comments_tenant_id"), table_name="comments")
    op.drop_index(op.f("ix_comments_target_id"), table_name="comments")
    op.drop_table("comments")
    # ### end Alembic commands ###
