"""create_collection_chat_messages_table

Revision ID: 42f3060e4bc3
Revises: 6b7f1c2d4e5a
Create Date: 2026-07-06 15:51:27.627450

"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "42f3060e4bc3"
down_revision = "6b7f1c2d4e5a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collection_chat_messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("collection_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("message", sa.String(length=4096), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["collection_id"], ["document_collections.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_collection_chat_messages_collection_id"),
        "collection_chat_messages",
        ["collection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_collection_chat_messages_user_id"),
        "collection_chat_messages",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_collection_chat_messages_user_id"),
        table_name="collection_chat_messages",
    )
    op.drop_index(
        op.f("ix_collection_chat_messages_collection_id"),
        table_name="collection_chat_messages",
    )
    op.drop_table("collection_chat_messages")
    # ### end Alembic commands ###
