"""add_versioning_to_documents

Revision ID: 7f7c3f5bfae7
Revises: fe4e754c86f2
Create Date: 2026-03-02 14:41:58.082448
"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "7f7c3f5bfae7"
down_revision = "fe4e754c86f2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_audit_logs_tenant_action_created_at", table_name="audit_logs")
    op.drop_index("ix_audit_logs_tenant_created_at", table_name="audit_logs")
    op.drop_index(
        "ix_chunk_embeddings_embedding_hnsw",
        table_name="chunk_embeddings",
        postgresql_using="hnsw",
    )
    op.drop_index("ix_chunk_embeddings_tenant_created_at", table_name="chunk_embeddings")
    op.drop_index("ix_data_deletions_tenant_requested_at", table_name="data_deletions")
    op.drop_index("ix_data_deletions_tenant_status_requested_at", table_name="data_deletions")
    op.drop_index("ix_document_chunks_fts", table_name="document_chunks", postgresql_using="gin")
    op.drop_index("ix_document_chunks_tenant_created_at", table_name="document_chunks")
    op.add_column("documents", sa.Column("parent_document_id", sa.UUID(), nullable=True))
    op.add_column(
        "documents",
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
    )
    op.drop_index("ix_documents_tenant_created_at", table_name="documents")
    op.drop_index("ix_documents_tenant_status", table_name="documents")
    op.create_foreign_key(
        None,
        "documents",
        "documents",
        ["parent_document_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_index("ix_idempotency_keys_tenant_created_at", table_name="idempotency_keys")
    op.drop_index("ix_ingestion_jobs_tenant_created_at", table_name="ingestion_jobs")
    op.drop_index("ix_ingestion_jobs_tenant_document", table_name="ingestion_jobs")
    op.drop_index("ix_ingestion_jobs_tenant_status", table_name="ingestion_jobs")
    op.drop_index("ix_queries_tenant_created_at", table_name="queries")
    op.drop_index("ix_queries_tenant_user_created_at", table_name="queries")
    op.drop_index("ix_query_citations_tenant_document", table_name="query_citations")
    op.drop_index("ix_query_citations_tenant_query", table_name="query_citations")
    op.drop_index("ix_refresh_tokens_tenant_expires", table_name="refresh_tokens")
    op.drop_index("ix_refresh_tokens_tenant_user_revoked", table_name="refresh_tokens")
    op.drop_index("ix_user_roles_tenant_user", table_name="user_roles")
    op.drop_index("ix_users_tenant_created_at", table_name="users")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_users_tenant_created_at", "users", ["tenant_id", "created_at"], unique=False
    )
    op.create_index(
        "ix_user_roles_tenant_user",
        "user_roles",
        ["tenant_id", "user_id"],
        unique=False,
    )
    op.create_index(
        "ix_refresh_tokens_tenant_user_revoked",
        "refresh_tokens",
        ["tenant_id", "user_id", "revoked_at"],
        unique=False,
    )
    op.create_index(
        "ix_refresh_tokens_tenant_expires",
        "refresh_tokens",
        ["tenant_id", "expires_at"],
        unique=False,
    )
    op.create_index(
        "ix_query_citations_tenant_query",
        "query_citations",
        ["tenant_id", "query_id"],
        unique=False,
    )
    op.create_index(
        "ix_query_citations_tenant_document",
        "query_citations",
        ["tenant_id", "document_id"],
        unique=False,
    )
    op.create_index(
        "ix_queries_tenant_user_created_at",
        "queries",
        ["tenant_id", "user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_queries_tenant_created_at",
        "queries",
        ["tenant_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_ingestion_jobs_tenant_status",
        "ingestion_jobs",
        ["tenant_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_ingestion_jobs_tenant_document",
        "ingestion_jobs",
        ["tenant_id", "document_id"],
        unique=False,
    )
    op.create_index(
        "ix_ingestion_jobs_tenant_created_at",
        "ingestion_jobs",
        ["tenant_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_idempotency_keys_tenant_created_at",
        "idempotency_keys",
        ["tenant_id", "created_at"],
        unique=False,
    )
    op.drop_constraint(None, "documents", type_="foreignkey")  # type: ignore[arg-type]
    op.create_index(
        "ix_documents_tenant_status", "documents", ["tenant_id", "status"], unique=False
    )
    op.create_index(
        "ix_documents_tenant_created_at",
        "documents",
        ["tenant_id", "created_at"],
        unique=False,
    )
    op.drop_column("documents", "version")
    op.drop_column("documents", "parent_document_id")
    op.create_index(
        "ix_document_chunks_tenant_created_at",
        "document_chunks",
        ["tenant_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_document_chunks_fts",
        "document_chunks",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_data_deletions_tenant_status_requested_at",
        "data_deletions",
        ["tenant_id", "status", "requested_at"],
        unique=False,
    )
    op.create_index(
        "ix_data_deletions_tenant_requested_at",
        "data_deletions",
        ["tenant_id", "requested_at"],
        unique=False,
    )
    op.create_index(
        "ix_chunk_embeddings_tenant_created_at",
        "chunk_embeddings",
        ["tenant_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_chunk_embeddings_embedding_hnsw",
        "chunk_embeddings",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
    )
    op.create_index(
        "ix_audit_logs_tenant_created_at",
        "audit_logs",
        ["tenant_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_audit_logs_tenant_action_created_at",
        "audit_logs",
        ["tenant_id", "action", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###
