"""add dead letter reason

Revision ID: 84b0e3e445d3
Revises: 20260302_0008
Create Date: 2026-03-02 11:15:11.459798
"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "84b0e3e445d3"
down_revision = "20260302_0008"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ingestion_jobs",
        sa.Column("dead_letter_reason", sa.String(length=64), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_users_tenant_created_at", "users", ["tenant_id", "created_at"], unique=False
    )
    op.create_index(
        "ix_user_roles_tenant_user",
        "user_roles",
        ["tenant_id", "user_id"],
        unique=False,
    )
    op.create_index(
        "ix_refresh_tokens_tenant_user_revoked",
        "refresh_tokens",
        ["tenant_id", "user_id", "revoked_at"],
        unique=False,
    )
    op.create_index(
        "ix_refresh_tokens_tenant_expires",
        "refresh_tokens",
        ["tenant_id", "expires_at"],
        unique=False,
    )
    op.create_index(
        "ix_query_citations_tenant_query",
        "query_citations",
        ["tenant_id", "query_id"],
        unique=False,
    )
    op.create_index(
        "ix_query_citations_tenant_document",
        "query_citations",
        ["tenant_id", "document_id"],
        unique=False,
    )
    op.create_index(
        "ix_queries_tenant_user_created_at",
        "queries",
        ["tenant_id", "user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_queries_tenant_created_at",
        "queries",
        ["tenant_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_ingestion_jobs_tenant_status",
        "ingestion_jobs",
        ["tenant_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_ingestion_jobs_tenant_document",
        "ingestion_jobs",
        ["tenant_id", "document_id"],
        unique=False,
    )
    op.create_index(
        "ix_ingestion_jobs_tenant_created_at",
        "ingestion_jobs",
        ["tenant_id", "created_at"],
        unique=False,
    )
    op.drop_column("ingestion_jobs", "dead_letter_reason")
    op.create_index(
        "ix_idempotency_keys_tenant_created_at",
        "idempotency_keys",
        ["tenant_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_documents_tenant_status", "documents", ["tenant_id", "status"], unique=False
    )
    op.create_index(
        "ix_documents_tenant_created_at",
        "documents",
        ["tenant_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_document_chunks_tenant_created_at",
        "document_chunks",
        ["tenant_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_data_deletions_tenant_status_requested_at",
        "data_deletions",
        ["tenant_id", "status", "requested_at"],
        unique=False,
    )
    op.create_index(
        "ix_data_deletions_tenant_requested_at",
        "data_deletions",
        ["tenant_id", "requested_at"],
        unique=False,
    )
    op.create_index(
        "ix_chunk_embeddings_tenant_created_at",
        "chunk_embeddings",
        ["tenant_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_chunk_embeddings_embedding_hnsw",
        "chunk_embeddings",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
    )
    op.create_index(
        "ix_audit_logs_tenant_created_at",
        "audit_logs",
        ["tenant_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_audit_logs_tenant_action_created_at",
        "audit_logs",
        ["tenant_id", "action", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###
