export const TOOL_LABELS: Record<string, string> = {
  search_ecosystem_docs: "Exploring Knowledge Base",
  web_search: "Searching the Web",
  crawl_url: "Analyzing URL Content",
  sync_connector: "Syncing Data Source",
  list_connectors: "Checking Integrations",
  get_connector_status: "Verifying Connection",
  gmail_search: "Searching Email",
  gmail_read: "Reading Correspondence",
  gmail_send: "Drafting Email",
  gmail_manage: "Managing Inbox",
  calendar_list_events: "Checking Schedule",
  calendar_find_free_slots: "Finding Availability",
  calendar_create_event: "Scheduling Event",
  notion_create_page: "Building Notion Page",
  notion_append_content: "Updating Document",
  github_search: "Exploring Repository",
  github_read_file: "Reading Repository File",
  drive_search: "Searching Drive",
  drive_read_file: "Reading Drive File",
  list_dir: "Exploring File System",
  read_file: "Reading File",
  write_file: "Writing to File",
  edit_file: "Surgical Code Edit",
  bash: "Executing Persistent Shell",
  run_command: "Terminal Command",
  glob: "Pattern Matching",
  grep: "Content Search (Regex)",
  notebook_edit: "Editing Notebook",
  web_fetch: "Extracting Page Data",
  todo_write: "Updating Task Ledger",
  todo_read: "Reviewing Progress",
  memory_write: "Storing Discovery",
  memory_read: "Recalling Context",
  memory_search: "Searching Memories",
  task: "Spawning Sub-Agent",
  ask_user_question: "Clarifying Objective",
  bash_output: "Monitoring Background Task",
  kill_shell: "Terminating Process",
  enter_plan_mode: "Designing Strategy (Plan Mode)",
  exit_plan_mode: "Entering Execution Mode",
  skill: "Invoking Specialized Skill",
  slash_command: "Executing Slash Command",
  data_analyze: "Analyzing Structured Data",
  document_convert: "Converting Document Format",
  observing: "Observation",
};
