import { jsPDF } from "jspdf";
import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } from "docx";
import toast from "react-hot-toast";

/**
 * Compiles a structured answer or plain text into a downloadable Markdown file.
 */
export const exportToMarkdown = (content: string, title: string = "AverQel AI Analysis") => {
  try {
    let markdown = `# ${title}\n\n`;

    try {
      const parsed = JSON.parse(
        content
          .replace(/```json/gi, "")
          .replace(/```/g, "")
          .trim(),
      );

      if (parsed.key_findings) {
        markdown += `## Key Findings\n`;
        parsed.key_findings.forEach((f: string) => {
          markdown += `- ${f}\n`;
        });
        markdown += `\n`;
      }

      if (parsed.detailed_analysis) {
        markdown += `## Detailed Analysis\n${parsed.detailed_analysis}\n\n`;
      }

      if (parsed.limitations) {
        markdown += `## Limitations & Uncertainties\n${parsed.limitations}\n\n`;
      }
    } catch {
      markdown += content;
    }

    const blob = new Blob([markdown], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `averqel-export-${new Date().getTime()}.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    toast.success("Markdown exported successfully");
  } catch (error) {
    console.error("Markdown export failed", error);
    toast.error("Failed to export Markdown");
  }
};

/**
 * Compiles a structured answer or plain text into a downloadable PDF file.
 */
export const exportToPDF = (content: string, title: string = "AverQel AI Analysis") => {
  try {
    const doc = new jsPDF();
    const margin = 20;
    const pageWidth = doc.internal.pageSize.getWidth();
    const maxLineWidth = pageWidth - margin * 2;
    let yPos = 20;

    // Header
    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.setTextColor(37, 99, 235); // Blue-600
    doc.text(title, margin, yPos);
    yPos += 10;

    doc.setFontSize(10);
    doc.setTextColor(107, 114, 128); // Gray-500
    doc.text(`Generated by AverQel AI on ${new Date().toLocaleString()}`, margin, yPos);
    yPos += 15;

    // Line separator
    doc.setDrawColor(229, 231, 235); // Gray-200
    doc.line(margin, yPos, pageWidth - margin, yPos);
    yPos += 15;

    const addText = (
      text: string,
      size: number = 11,
      font: string = "normal",
      color: [number, number, number] = [31, 41, 55],
    ) => {
      doc.setFont("helvetica", font);
      doc.setFontSize(size);
      doc.setTextColor(color[0], color[1], color[2]);

      const lines = doc.splitTextToSize(text, maxLineWidth);
      lines.forEach((line: string) => {
        if (yPos > 270) {
          doc.addPage();
          yPos = 20;
        }
        doc.text(line, margin, yPos);
        yPos += size * 0.5 + 2;
      });
      yPos += 5;
    };

    try {
      const parsed = JSON.parse(
        content
          .replace(/```json/gi, "")
          .replace(/```/g, "")
          .trim(),
      );

      if (parsed.key_findings) {
        addText("Key Findings", 16, "bold", [17, 24, 39]);
        parsed.key_findings.forEach((f: string) => {
          addText(`• ${f}`, 11);
        });
      }

      if (parsed.detailed_analysis) {
        addText("Detailed Analysis", 16, "bold", [17, 24, 39]);
        addText(parsed.detailed_analysis, 11);
      }

      if (parsed.limitations) {
        addText("Limitations", 16, "bold", [17, 24, 39]);
        addText(parsed.limitations, 11);
      }
    } catch {
      addText(content, 11);
    }

    doc.save(`averqel-export-${new Date().getTime()}.pdf`);
    toast.success("PDF exported successfully");
  } catch (error) {
    console.error("PDF export failed", error);
    toast.error("Failed to export PDF");
  }
};

/**
 * Compiles a structured answer or plain text into a downloadable DOCX file.
 */
export const exportToDocx = async (content: string, title: string = "AverQel AI Analysis") => {
  try {
    const children: Paragraph[] = [
      new Paragraph({
        text: title,
        heading: HeadingLevel.HEADING_1,
        alignment: AlignmentType.CENTER,
        spacing: { after: 400 },
      }),
      new Paragraph({
        children: [
          new TextRun({
            text: `Generated by AverQel AI on ${new Date().toLocaleString()}`,
            color: "6B7280",
            size: 20,
          }),
        ],
        spacing: { after: 600 },
      }),
    ];

    try {
      const parsed = JSON.parse(
        content
          .replace(/```json/gi, "")
          .replace(/```/g, "")
          .trim(),
      );

      if (parsed.key_findings) {
        children.push(
          new Paragraph({
            text: "Key Findings",
            heading: HeadingLevel.HEADING_2,
            spacing: { before: 400, after: 200 },
          }),
        );
        parsed.key_findings.forEach((f: string) => {
          children.push(new Paragraph({ text: f, bullet: { level: 0 } }));
        });
      }

      if (parsed.detailed_analysis) {
        children.push(
          new Paragraph({
            text: "Detailed Analysis",
            heading: HeadingLevel.HEADING_2,
            spacing: { before: 400, after: 200 },
          }),
        );
        children.push(new Paragraph({ text: parsed.detailed_analysis }));
      }

      if (parsed.limitations) {
        children.push(
          new Paragraph({
            text: "Limitations",
            heading: HeadingLevel.HEADING_2,
            spacing: { before: 400, after: 200 },
          }),
        );
        children.push(new Paragraph({ text: parsed.limitations }));
      }
    } catch {
      children.push(new Paragraph({ text: content }));
    }

    const doc = new Document({
      sections: [{ children }],
    });

    const blob = await Packer.toBlob(doc);
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `averqel-export-${new Date().getTime()}.docx`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    toast.success("DOCX exported successfully");
  } catch (error) {
    console.error("DOCX export failed", error);
    toast.error("Failed to export DOCX");
  }
};
